# Generated by Django 4.2.11 on 2024-06-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='agents/')),
                ('jioned_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
