# Generated by Django 4.2.11 on 2024-06-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.TextField(max_length=500)),
                ('cat_image', models.ImageField(upload_to='category/')),
                ('slug', models.CharField(max_length=40)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
