# Generated by Django 4.2.11 on 2024-06-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='property/')),
                ('number_of_beds', models.IntegerField()),
                ('number_of_baths', models.IntegerField()),
                ('normal_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('slug', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
