# Generated by Django 4.2.11 on 2024-07-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'property', 'verbose_name_plural': 'properties'},
        ),
    ]
